/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.svvyat.ipc;

public class App {

    public static void main(String[] args) {
        System.out.println(new IpLinesCounter().calculateDistinct(args[0]));
    }
}
