/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.svvyat.ipc;

import org.junit.jupiter.api.Test;

import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test
    void testCalculator(){
        System.out.println(Paths.get("").toAbsolutePath());
        var count = new IpLinesCalculator().calculateDistinct("../ips.list");
        assertEquals(3695845, count);
    }
}
