/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.svvyat.ipc;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class IpLinesCounterTest {

    /**
     * ../ips.list автоматически сгенерирован с помощью библиотеки faker
     * и вручную добавил несколько строк случайных строк, для проверки, что считаются только IP
     * $wc -l ips.list
     * 8647816 ips.list
     */
    @Test
    void testCountOnBigFile(){
        var count = new IpLinesCounter().calculateDistinct("../ips.list");
        assertEquals(3695845, count);
    }
}
